version: '3.9'

services:

  postgres:
    container_name: Dip_Calendar
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - backend_nw
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge
